### PR TITLE
Change mapping format for better gzip compression

### PR DESCRIPTION
**Pull request by subzey**
Wow, those stripped 90 gzipped bytes took longer than I was expecting!

The core idea is `convert.js` signature was changed from `(mapping: {[key: string]: value: string})` to `(keys: string, values: string)`:

```js
convert(
  "qwerty...",
  "йцукен..."
)
```

As no one in the Galaxy would be able to write these mapping strings manually with the first try, I've added a build script.

*Source layouts* are in `/src/layouts/*.json` and are just key->value maps, just like before.

The *built module* is in `/dist/` (.gitignored). When publishing to npm, you should call `npm publish` from the `/dist/` directory! In order to prevent publishing from the root `/`, a `private` field was added to package.json.

- All `layouts/*.json` are converted to the corresponding `.js` files. There's no hardcoded list, so it's somewhat more easy to add new layouts.
- `index.js` contents are generated automatically.
- `COPYING`, `README` and `CHANGELOG` are just copied as-is
- `package.json` is copied into `/dist/` *with some fields removed*:
  - `private` is removed, so you can publish it
  - `scripts`, `jest`, `devDependencies`, `eslintConfig`, `lint-staged`, `pre-commit`, `size-limit` are removed, because these are useless for the end-user.

The result is small and tidy package ready to be published with no need for `.npmignore` and stuff.

Tests are green, coverage is 100%.

### CODE REVIEW

**Comment by ai** [comment]
The way is good, my main concern only directories.

What do you think about:

1. Origin files will be in `/*.json`.
2. Build locales will be in the same `/*.js`.
3. Build files will be ignored by `??.js` (2 symbols with `.js` ext).
4. We will call `build` script on `prepublish`.

**Comment by ai** [comment]
@subzey you don’t need to fix copy script in the way that I suggested ;).

**Comment by subzey** [comment]
Aaactually, I generally prefer do not mix up the source and the built files: a project git root is not necessary have to be the package root. And [this](https://twitter.com/subzey/status/895671092643102720).

I could change the PR target branch so you could merge it into some temporary branch and tune and tweak the code until you like it

**Comment by ai** [comment]
I have same thought but after many years of PostCSS experience (we have the same building to `build/` process) I tired.

There is no way to install dependency from `npm`. It is easy to forget and write `npm publish` from the root. And it is just more complex.

**Comment by ai** [comment]
I agree with your concerns about unnecessary build settings in `package.json`. But now solution looks more complex ;). Maybe a better solution will be some `npm publish` replacement? `npm-publisher`, which will clean `package.json` during `publish`?

**Comment by subzey** [comment]
@ai the project is now built into `/`. Added `prepublish` hook: build and test. Please review

**Comment by ai** [comment]
Everythings looks good. Just wait when you will finish :D.

Also, it will be good to insert trailing `\n` to JSON files according `.editorconfig`.

**Comment by ai** [comment]
@subzey Do we ready for release?

**Comment by subzey** [comment]
@ai, sure!

**Pull request merged**
