### PR TITLE
Bug/missing characters

### PR DESCRIPTION
**Pull request by Jokero**
```js
'|': '/',
':': 'Ж'
```

### CODE REVIEW

**Comment by Jokero** [comment]
And I suggest to change layouts format because they are unreadable.

Now:
```js
{
    'q': 'й',
    'w': 'ц',
    'e': 'у',
    'r': 'к',
    't': 'е',
    'y': 'н',
    'u': 'г',
    'i': 'ш',
    'o': 'щ',
    'p': 'з',
    '[': 'х',
    '{': 'Х',
    ']': 'ъ',
    '}': 'Ъ',
    '|': '/',
    '`': 'ё',
    '~': 'Ё',
    'a': 'ф',
    's': 'ы',
    'd': 'в',
    'f': 'а',
    'g': 'п',
    'h': 'р',
    'j': 'о',
    'k': 'л',
    'l': 'д',
    ';': 'ж',
    ':': 'Ж',
    "'": 'э',
    '"': 'Э',
    'z': 'я',
    'x': 'ч',
    'c': 'с',
    'v': 'м',
    'b': 'и',
    'n': 'т',
    'm': 'ь',
    ',': 'б',
    '<': 'Б',
    '.': 'ю',
    '>': 'Ю',
    '/': '.',
    '?': ',',
    '@': '"',
    '#': '№',
    '$': ';',
    '^': ':',
    '&': '?'
}
```

My suggestion (like on keyboard, perfectly readable and easy to see the mistake):
```js
{
    '`': 'ё',
    '~': 'Ё', '@': '"', '#': '№', '$': ';', '^': ':', '&': '?',

    'q': 'й', 'w': 'ц', 'e': 'у', 'r': 'к', 't': 'е', 'y': 'н', 'u': 'г', 'i': 'ш', 'o': 'щ', 'p': 'з', '[': 'х', ']': 'ъ',
                                                                                                        '{': 'Х', '}': 'Ъ', '|': '/',

    'a': 'ф', 's': 'ы', 'd': 'в', 'f': 'а', 'g': 'п', 'h': 'р', 'j': 'о', 'k': 'л', 'l': 'д', ';': 'ж', "'": 'э',
                                                                                              ':': 'Ж', '"': 'Э',

    'z': 'я', 'x': 'ч', 'c': 'с', 'v': 'м', 'b': 'и', 'n': 'т', 'm': 'ь', ',': 'б', '.': 'ю', '/': '.',
                                                                          '<': 'Б', '>': 'Ю', '?': ','
}
```

**Comment by ai** [comment]
Is it will be possible to keep 80/120 columns line limit with your suggestion?

**Comment by ai** [comment]
Released in 0.4.1

**Comment by Jokero** [comment]
@ai Max line length is slightly more (134). But we can don't set limits for maps because these limits do not improve readability. Working example:

```js
var convert = require('./convert');

/* eslint-disable max-len, indent */

var map = {
    '`': 'ё',
    '~': 'Ё', '@': '"', '#': '№', '$': ';', '^': ':', '&': '?',

    'q': 'й', 'w': 'ц', 'e': 'у', 'r': 'к', 't': 'е', 'y': 'н', 'u': 'г', 'i': 'ш', 'o': 'щ', 'p': 'з', '[': 'х', ']': 'ъ',
                                                                                                        '{': 'Х', '}': 'Ъ', '|': '/',

    'a': 'ф', 's': 'ы', 'd': 'в', 'f': 'а', 'g': 'п', 'h': 'р', 'j': 'о', 'k': 'л', 'l': 'д', ';': 'ж', "'": 'э',
                                                                                              ':': 'Ж', '"': 'Э',

    'z': 'я', 'x': 'ч', 'c': 'с', 'v': 'м', 'b': 'и', 'n': 'т', 'm': 'ь', ',': 'б', '.': 'ю', '/': '.',
                                                                          '<': 'Б', '>': 'Ю', '?': ','
};

/* eslint-enable max-len */

module.exports = convert(map);
```

**Comment by ai** [comment]
Can you opn a separate issue. I will think for a day.

We can disable `max-len` if we decide ot use it.

**Pull request merged**
