### PR TITLE
Add german layout mapping

### PR DESCRIPTION
**Pull request by lebedev-yury**

### CODE REVIEW

**Comment by lebedev-yury** [comment]
1. Rebased and fixed the order in the Readme
2. Not sure what is here with the syntax formatting. Is it because of the `#` character?

**Comment by ai** [comment]
Because `"\"` should be replaced to `"\\"`

**Comment by lebedev-yury** [comment]
Fixed the '\' character aswell.
Linter complains now about the missing space before values, which is strange, because they are present.

Btw, thanks for a cool library!

**Comment by lebedev-yury** [comment]
Fixed

**Pull request merged**
