### PR TITLE
Add Dvorak and Colemak keyboard layouts for the English language

### PR DESCRIPTION
**Pull request by abhinavk99**
Dvorak keybinds are in `dv.json`
Colemak keybinds are in `co.json`

### CODE REVIEW

**Comment by abhinavk99** [comment]
The Travis CI build says Colemak is a typo, I'm not really sure how to fix that.

**Comment by ai** [comment]
Hi. Thanks for PR. Everything looks good. Don’t worry, I will fix spell checker.

Right now I am preparing for a conference talk. SO I will accept this PR and release it on this weekend of on next week. Hope you don’t need it very soon :).

**Comment by ai** [comment]
If you want to fix spelling check warning by yourself, you can add `Colemak` word to `.yaspellerrc`.

**Comment by ai** [comment]
Released in 0.7 version

**Comment by ai** [comment]
I renamed layout files to `dvorak.json` and `colemak.json` since 2 symbol names are for languages

**Comment by abhinavk99** [comment]
Alright, thanks

**Pull request merged**
